title: What's going on
author: Abhishek Maderana
email: maderanaabhishek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Starting with title What's going on, this blog is meant to cover
  new things i come around and wants to share with community from
  my understanding.

# social links
twitter_username: will be around in some time
github_username:  Maderana

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
